### ISSUE TITLE
Mvn error

### ISSUE THREAD

**Issue by juandavidvillacalle** [TylerJewell/che-plugin-archetype#1]
Hi,

I am new to mvn and I am having this problem when trying to use your tool. Can you give me any insights?

![capture](https://cloud.githubusercontent.com/assets/5877373/10430804/8c9a47d8-7101-11e5-8f54-cea2614adf8f.PNG)

**Comment by TylerJewell** [comment]
Hi Juan:

Can you give me some details.  Please let me know the steps (and commands)
that you took to checkout the archetype and then to run it.

Did you run "mvn clean install" inside the maven archetype directory before
you tried to generate the plug-in?

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by juandavidvillacalle** [comment]
Thanks for your quick reply!

These are the steps that I followed:

git clone https://github.com/tylerjewell/che-plugin-archetype
cd che-plugin-archetype
mvn clean install
cd ..

mvn archetype:generate -B -DarchetypeGroupId=org.eclipse.che.examples -DarchetypeArtifactId=che-plugin-archetype -DarchetypeVersion=1.0-SNAPSHOT -DgroupId=juan_define_a_package_name -DartifactId=juan_define_an_artifactId -Dversion=juan_define_a_version_1 -DpluginClassName=Juan_define_a_class_name_of_new_plugin

cd juan_define_an_artifactId
mvn clean install

Then I copied the jar juan_define_an_artifactId-juan_define_a_version_1.jar to

C:\Users\jvillaca\AppData\Local\Programs\Eclipse-Che-3.12\ext

Finally I ran extInstall.bat and that's where I got the error that i attached on the first message

**Comment by juandavidvillacalle** [comment]
This is how my mvn repo looks like regarding the dependency that is not being found:

![image](https://cloud.githubusercontent.com/assets/5877373/10432458/743f604c-710b-11e5-8bc5-daeeec7fc730.png)

![image](https://cloud.githubusercontent.com/assets/5877373/10432471/8662a98c-710b-11e5-9505-e60f226855ab.png)

![image](https://cloud.githubusercontent.com/assets/5877373/10432486/9c5597ae-710b-11e5-9e85-645c877a6cda.png)

**Comment by TylerJewell** [comment]
Hi Juan:

I haven't been able to reproduce the problem fully yet, but I think it's
happening because the archetype generator is generating a plug-in version
that somehow doesn't match the Che version you have installed.

Can you confirm that you have Che version 3.12.5.2?  If so, I believe the
generator is creating a plug-in for 3.12.5.

If so, one way to test this is:
1. cd juan_define_an_artifactId
2. In the pom.xml file that is in this directory, *replace* the <parent>
tag at the beginning with.
3. In this directory, mvn clean install.

Then use this new plug-in JAR file and rerun the extInstall.bat file.

<parent> <artifactId>maven-depmgt-pom</artifactId> <groupId
>org.eclipse.che.depmgt</groupId> <version>3.12.5.2</version> </parent>
Sorry for these challenges.  For what it is worth, in 3.13, we are
releasing a much simpler plug-in add / remove model.  It'll be drag and
drop into a dashboard that lives within Che.  It'll handle some of these
versioning issues more naturally.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by juandavidvillacalle** [comment]
Hi Tyler,

Yes, my version of Che is 3.12.5.2 
![image](https://cloud.githubusercontent.com/assets/5877373/10448928/816ef81a-7190-11e5-8aec-f05f656aabd5.png)


I changed the pom.xlml with the changes you suggested and it now looks like this:

![image](https://cloud.githubusercontent.com/assets/5877373/10448991/e3484064-7190-11e5-9766-9cd9654f006c.png)

Then I ran mvn clean install and I got build success:

![image](https://cloud.githubusercontent.com/assets/5877373/10449081/61e160b8-7191-11e5-85d1-ba6c94aeba61.png)


However when I run extInstall.bat I get a new error:

![image](https://cloud.githubusercontent.com/assets/5877373/10449120/b273a5d6-7191-11e5-9240-41463d98809e.png)

**Comment by TylerJewell** [comment]
Juan:

Yes, this is an unusual issue.  Your plug-in is getting built correctly,
but Che is not reassembling itself properly for some reason.  The
particular error usually means that there is some sort of lookup issue, but
when I do a clean install, I do not reproduce the issue myself.

If you can humor me - give me 24 more hours.  We will give you an early
access to 3.13, and this includes a number of simplifications:
1. We will have centralized the plug-in generator archetype.
2. You can generate plug-ins that are client-side or server-side separately.
3. Plug-ins get packaged into a ZIP file that is an assembly itself.
4. You can then do drag & drop of new plug-in ZIP files into Che, which
will include a Web dashboard for managing your plug-ins.

If you give me 24 hours, i can get you instructions on how to go through
this sequence and it should be tremendously better for you.

Tyler

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by juandavidvillacalle** [comment]
You are right :+1: , it was a problem with Che (I had installed it using the installer for windows).

In order to fix the problem: 
1) I deleted my local mvn repo
2) Installed Che from source (which repopulated my mvn repo)
3) Used Che from the binary install

This way when I ran extInstall.bat, Che was able to reassemble correctly.

However, I am still very interested in having early access to version 3.13.

**Comment by juandavidvillacalle** [comment]
I am posting this as a new message because it is more related to using the plugin that I generated with your archetype.

I thought that I would see a new plugin on the plugins list, but this is not the case:

![image](https://cloud.githubusercontent.com/assets/5877373/10483855/d6d45aba-7281-11e5-9401-b75845900d28.png)

Which brings me to this question: how can I interact with the plugin?

**Comment by TylerJewell** [comment]
Your plugin is there.   In the plugin code, there will be a "title=...."
text.  In the plugin you created, that text is "This is a pretty title to
give to an extension".  You can see it in the list on the right.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by juandavidvillacalle** [comment]
Thanks!

**Comment by TylerJewell** [comment]
This is great to hear.

The 3.13 build with the new plug-in model wasn't ready this morning.  I
hope it will be merged into the source branches today and then we'll update
the docs.  You can try that then.

We'll also upload a set of new maven archectype generators into our nexus
so they will work without you having to install anything additional on your
computer.

I hope it will be ready tomorrow.  You can see the new nature of plugins in
the early docs:
https://dash.readme.io/project/eclipse-che/v1.0/docs/plug-ins

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55
